### ISSUE TITLE
about libcudart .so.9.0?

### ISSUE THREAD

**Issue by DurriyaDo** [garrickbrazil/M3D-RPN#14]

**Comment by DurriyaDo** [comment]
i have met several problems,the finally is : 
m3d_rpn/lib/loss/rpn_3d.py", line 125, in forward
src_anchors = self.anchors[rois[:, 4].type(torch.cuda.LongTensor), :]
File "/home/dev-aug/.local/lib/python3.6/site-packages/torch/tensor.py", line 412, in array
return self.numpy()
TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
i have referred the before one which is the same with me.But it doesn't work on my computer.Then i change ".numpy()" to ".cpu().numpy()" (about 2 places)in the "tensor.py" file,and it worked.
